name = "schema-do"
route = { pattern = "*/*", zone_name = "schema.do" }
main = "worker.js"
compatibility_date = "2022-08-25"
node_compat = true

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]
